// src/components/features/service-bookings/garageJobs.ts
// Master list of garage/fleet job items for the "work required" picker.
// Deduplicated, first-occurrence order preserved. Source: user-supplied
// Garage_Jobs_Dropdown_List. Plain English trade terms (not i18n'd —
// garage jargon is used as-is across languages; the free-text "custom
// work" field covers anything not listed here).

/** Shown as one-tap chips above the search box — a symmetrical 3 × 2 grid. */
export const QUICK_JOBS: string[] = [
  // Row 1
  'Oil Service',
  'Tyre Replacement',
  'MOT Check',
  // Row 2
  'Front Brake Pads',
  'Rear Brake Pads',
  'Pre-Rental Inspection',
]

/** Full searchable list (deduped). */
export const GARAGE_JOBS: string[] = [
  // Top quick-pick / inspections
  'Diagnostic Check',
  'Pre-Delivery Inspection (PDI)',
  'Pre-Handover Inspection',
  'Pre-Rental Inspection',
  'Check-In / Return Inspection',
  'Check-Out Inspection',
  'Vehicle Health Check',
  'Oil Service',
  'Interim Service',
  'Full Service',
  'Major Service',
  'AdBlue Top-Up',
  'Front Brake Pads',
  'Rear Brake Pads',
  'Front Brake Discs',
  'Rear Brake Discs',
  'Front Pads & Discs',
  'Rear Pads & Discs',
  'Battery Test',
  'Battery Replacement',
  'Flat Battery / Jump Start',
  'Tyre Replacement',
  'Puncture Repair',
  'Wheel Balancing',
  'Wheel Alignment / Tracking',
  'Suspension Noise Check',
  'MOT Check',
  'MOT Repairs',
  'Bulb Replacement',
  'Wiper Blade Replacement',
  'Non-Starter Diagnostic',

  // Service / maintenance
  'Oil & Filter Change',
  'Air Filter Replacement',
  'Cabin / Pollen Filter Replacement',
  'Fuel Filter Replacement',
  'Spark Plug Replacement',
  'Glow Plug Replacement',
  'Transmission Oil Change',
  'Gearbox Oil Change',
  'Differential Oil Change',
  'Brake Fluid Change',
  'Coolant Change',
  'Coolant Top-Up',
  'Screenwash Top-Up',
  'Power Steering Fluid Top-Up',
  'General Vehicle Inspection',
  'Pre-MOT Inspection',
  'Service Light Reset',
  'Maintenance Inspection',
  'Safety Inspection',
  'Road Test',
  'Quality Control Check',
  'Final Inspection',

  // Brakes
  'Brake Caliper - OSF',
  'Brake Caliper - NSF',
  'Brake Caliper - OSR',
  'Brake Caliper - NSR',
  'Brake Hose - Front',
  'Brake Hose - Rear',
  'Brake Pipe Repair',
  'Handbrake Adjustment',
  'Handbrake Cable',
  'Electronic Parking Brake Fault',
  'ABS Sensor - OSF',
  'ABS Sensor - NSF',
  'ABS Sensor - OSR',
  'ABS Sensor - NSR',
  'ABS Diagnostic',
  'Brake Warning Light',
  'Brake Noise Check',
  'Brake Binding Check',
  'Brake Pedal Fault',
  'Brake Servo Fault',
  'Master Cylinder',
  'Rear Brake Shoes',
  'Brake Drum',
  'Brake Pad Wear Sensor',
  'Brake System Bleed',

  // Tyres / wheels
  'Front Tyre Replacement',
  'Rear Tyre Replacement',
  'OSF Tyre',
  'NSF Tyre',
  'OSR Tyre',
  'NSR Tyre',
  'Tyre Valve Replacement',
  'TPMS Sensor Replacement',
  'TPMS Reset',
  '4 Wheel Alignment',
  'Wheel Nut Replacement',
  'Locking Wheel Nut Removal',
  'Alloy Wheel Repair',
  'Steel Wheel Replacement',
  'Wheel Bearing - OSF',
  'Wheel Bearing - NSF',
  'Wheel Bearing - OSR',
  'Wheel Bearing - NSR',
  'Spare Wheel Fitment',
  'Tyre Pressure Check',
  'Tyre Rotation',
  'Wheel Inspection',
  'Damaged Wheel Check',

  // Suspension / steering
  'Front Shock Absorber',
  'Rear Shock Absorber',
  'Front Coil Spring',
  'Rear Coil Spring',
  'OSF Shock Absorber',
  'NSF Shock Absorber',
  'OSR Shock Absorber',
  'NSR Shock Absorber',
  'OSF Coil Spring',
  'NSF Coil Spring',
  'OSR Coil Spring',
  'NSR Coil Spring',
  'Lower Arm - OSF',
  'Lower Arm - NSF',
  'Upper Arm - OSF',
  'Upper Arm - NSF',
  'Ball Joint - OSF',
  'Ball Joint - NSF',
  'Track Rod End - OSF',
  'Track Rod End - NSF',
  'Inner Track Rod',
  'Drop Link - OSF',
  'Drop Link - NSF',
  'Drop Link - OSR',
  'Drop Link - NSR',
  'Anti-Roll Bar Bushes',
  'Suspension Bushes',
  'Subframe Bushes',
  'Steering Rack',
  'Power Steering Fault',
  'Steering Noise Check',
  'Vehicle Pulling Left/Right',
  'Steering Wheel Off Centre',
  'Power Steering Fluid Leak',
  'Wishbone Replacement',
  'Hub Assembly',
  'Strut Top Mount',
  'Strut Bearing',

  // Driveshaft / clutch / gearbox
  'OS Driveshaft',
  'NS Driveshaft',
  'Driveshaft Gaiter',
  'CV Joint',
  'Inner CV Joint',
  'Outer CV Joint',
  'Clutch Kit',
  'Clutch Diagnostic',
  'Clutch Slave Cylinder',
  'Clutch Master Cylinder',
  'Dual Mass Flywheel',
  'Flywheel Replacement',
  'Gearbox Diagnostic',
  'Gearbox Mount',
  'Gear Selector Cable',
  'Automatic Gearbox Fault',
  'Manual Gearbox Fault',
  'Transmission Leak',
  'Gearbox Oil Leak',
  'Clutch Pedal Fault',
  'Clutch Slip',
  'Clutch Noise',
  'Prop Shaft',
  'Differential Fault',

  // Engine / cooling
  'Engine Diagnostic',
  'Engine Noise Check',
  'Oil Leak Investigation',
  'Coolant Leak Investigation',
  'Overheating Investigation',
  'Timing Belt Kit',
  'Timing Chain Check',
  'Auxiliary Belt',
  'Fan Belt',
  'Water Pump',
  'Thermostat',
  'Radiator',
  'Radiator Fan',
  'Coolant Hose',
  'Expansion Tank',
  'Engine Mount',
  'Injector Fault',
  'Fuel Injector Replacement',
  'Fuel Pump',
  'Fuel Leak Investigation',
  'Turbo Fault',
  'Turbo Replacement',
  'Turbo Hose',
  'Intercooler Hose',
  'EGR Valve',
  'EGR Clean',
  'Throttle Body Clean',
  'MAF Sensor',
  'MAP Sensor',
  'Lambda Sensor',
  'Crankshaft Sensor',
  'Camshaft Sensor',
  'Oil Pressure Sensor',
  'Engine Misfire',
  'Starter Issue Investigation',
  'Rough Idle Investigation',
  'Loss of Power Investigation',
  'Engine Mount Replacement',
  'Fuel Filter Housing',
  'Coolant Pressure Test',
  'Oil Pressure Test',

  // Exhaust / emissions / AdBlue
  'AdBlue System Diagnostic',
  'AdBlue Injector',
  'AdBlue Pump',
  'AdBlue Tank',
  'AdBlue Pipe',
  'NOx Sensor',
  'NOx Sensor - Upstream',
  'NOx Sensor - Downstream',
  'DPF Diagnostic',
  'DPF Regeneration',
  'DPF Clean',
  'DPF Pressure Sensor',
  'Catalytic Converter',
  'Exhaust Repair',
  'Exhaust Replacement',
  'Exhaust Leak',
  'Back Box',
  'Middle Section Exhaust',
  'Front Pipe Exhaust',
  'Flexi Pipe',
  'Emissions Failure',
  'Smoke Test',
  'Diesel Smoke Test',
  'Exhaust Bracket',
  'Exhaust Clamp',
  'AdBlue Warning Light',
  'DPF Warning Light',
  'Emissions Warning Light',

  // Electrical / battery / starting
  'Alternator Replacement',
  'Starter Motor Replacement',
  'Charging System Diagnostic',
  'Parasitic Drain Test',
  'Fuse Replacement',
  'Relay Replacement',
  'Wiring Repair',
  'Earth Fault',
  'ECU Diagnostic',
  'Body Control Module Fault',
  'Central Locking Fault',
  'Key Programming',
  'Key Battery Replacement',
  'Immobiliser Fault',
  'Stop/Start Fault',
  'Dashboard Warning Light',
  'Instrument Cluster Fault',
  'Horn Fault',
  'Reverse Camera Fault',
  'Parking Sensor Fault',
  'Sensor Fault Diagnostic',
  'Battery Terminal Repair',
  'Battery Cable Repair',
  'Electrical Short Investigation',

  // Lights / visibility
  'Headlight Bulb',
  'Tail Light Bulb',
  'Brake Light Bulb',
  'Indicator Bulb',
  'Number Plate Bulb',
  'Fog Light Bulb',
  'Reverse Light Bulb',
  'Daytime Running Light',
  'Headlight Unit',
  'Rear Light Unit',
  'Headlight Aim Adjustment',
  'Front Wipers',
  'Rear Wiper',
  'Washer Pump',
  'Washer Jet',
  'Windscreen Chip Repair',
  'Windscreen Replacement',
  'Mirror Glass',
  'Door Mirror Unit',
  'Heated Mirror Fault',
  'Rain Sensor Fault',
  'Auto Lights Fault',
  'Fog Light Unit',
  'Indicator Unit',

  // Air conditioning / heating
  'Air Con Regas',
  'Air Con Diagnostic',
  'Air Con Leak Test',
  'Air Con Compressor',
  'Air Con Condenser',
  'Air Con Pipe',
  'Air Con Pressure Sensor',
  'Heater Not Working',
  'Blower Motor',
  'Heater Resistor',
  'Cooling Fan Fault',
  'Demister Fault',
  'Heater Matrix',
  'Climate Control Diagnostic',
  'Air Con Service',
  'Air Con Odour Treatment',

  // Body / doors / interior
  'Door Handle',
  'Door Lock',
  'Door Latch',
  'Window Regulator',
  'Electric Window Fault',
  'Seat Belt Fault',
  'Seat Repair',
  'Interior Trim Repair',
  'Bonnet Catch',
  'Boot Lock',
  'Sliding Door Fault',
  'Door Alignment',
  'Minor Body Repair',
  'Panel Damage',
  'Bumper Repair',
  'Mirror Replacement',
  'Number Plate Replacement',
  'Door Seal',
  'Bonnet Strut',
  'Tailgate Strut',
  'Interior Light Fault',
  'Dashboard Trim Repair',
  'Seat Adjustment Fault',
  'Glovebox Repair',
  'Fuel Flap Repair',

  // Van / fleet-specific
  'Load Door Fault',
  'Sliding Door Roller',
  'Sliding Door Handle',
  'Rear Door Lock',
  'Side Door Lock',
  'Bulkhead Repair',
  'Roof Rack Check',
  'Tow Bar Electrics',
  'Tow Bar Fitment',
  'Van Ply Lining Repair',
  'Vehicle Decal Removal',
  'Vehicle Decal Fitment',
  'Taxi Plate Fitment',
  'Private Hire Plate Fitment',
  'Dashcam Fitment',
  'Dashcam Removal',
  'Tracker Fitment',
  'Tracker Removal',
  'Speed Limiter Check',
  'Reversing Camera Fitment',
  'Parking Sensor Fitment',
  'Fleet Inspection',
  'Damage Inspection',
  'De-Fleet Inspection',
  'Vehicle Handover Check',
  'Vehicle Collection Check',
  'Vehicle Delivery Check',

  // MOT / compliance
  'MOT Failure Repairs',
  'MOT Advisory Check',
  'MOT Retest',
  'Brake Test',
  'Emissions Test',
  'Seat Belt Inspection',
  'Suspension Inspection',
  'Tyre Legal Check',
  'Number Plate Check',
  'Wiper Check',
  'Horn Check',
  'Warning Light Check',
  'Taxi Compliance Check',
  'Private Hire Compliance Check',
  'Roadworthiness Check',

  // Diagnostics / fault finding
  'Engine Management Light Diagnostic',
  'Warning Light Diagnostic',
  'Airbag Diagnostic',
  'Electrical Diagnostic',
  'Battery Drain Diagnostic',
  'Noise Investigation',
  'Vibration Investigation',
  'Loss of Power Diagnostic',
  'Overheating Diagnostic',
  'Coolant Leak Diagnostic',
  'Oil Leak Diagnostic',
  'Brake Noise Diagnostic',
  'Suspension Noise Diagnostic',
  'Steering Noise Diagnostic',
  'AdBlue Diagnostic',
  'Emissions Diagnostic',
  'Road Test Diagnostic',
]
